// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfw829zgNH7WiSn5_9AJWigNYRA_4pT0k',
    appId: '1:493072699110:web:276798a78a3ddaca2fb527',
    messagingSenderId: '493072699110',
    projectId: 'tachtechrnr',
    authDomain: 'tachtechrnr.firebaseapp.com',
    storageBucket: 'tachtechrnr.firebasestorage.app',
    measurementId: 'G-EG8E0TN3YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHXzCo7rSccDvROYzFDs0kX4Rw3sC75s',
    appId: '1:493072699110:android:f28ded07cfa0c2ef2fb527',
    messagingSenderId: '493072699110',
    projectId: 'tachtechrnr',
    storageBucket: 'tachtechrnr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRxUudnx0wPvO4wNd3MbPw7S-5dl-YbA',
    appId: '1:493072699110:ios:1c3e5451ca134f2a2fb527',
    messagingSenderId: '493072699110',
    projectId: 'tachtechrnr',
    storageBucket: 'tachtechrnr.firebasestorage.app',
    iosBundleId: 'com.example.mitreSalesTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRxUudnx0wPvO4wNd3MbPw7S-5dl-YbA',
    appId: '1:493072699110:ios:1c3e5451ca134f2a2fb527',
    messagingSenderId: '493072699110',
    projectId: 'tachtechrnr',
    storageBucket: 'tachtechrnr.firebasestorage.app',
    iosBundleId: 'com.example.mitreSalesTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfw829zgNH7WiSn5_9AJWigNYRA_4pT0k',
    appId: '1:493072699110:web:d6da732a0a3b06b92fb527',
    messagingSenderId: '493072699110',
    projectId: 'tachtechrnr',
    authDomain: 'tachtechrnr.firebaseapp.com',
    storageBucket: 'tachtechrnr.firebasestorage.app',
    measurementId: 'G-G4MFR66DE6',
  );

}